# Generated by Django 5.0.6 on 2024-05-11 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicatinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=100)),
                ('Taka', models.CharField(max_length=100)),
                ('firstdate', models.DateField()),
                ('lastdate', models.DateField()),
                ('totalsit', models.CharField(max_length=100)),
                ('Sci_sit', models.CharField(max_length=100)),
                ('arts_sit', models.CharField(max_length=100)),
                ('com_sit', models.CharField(max_length=100)),
                ('tec_adu_sit', models.CharField(max_length=100)),
                ('sci_qua', models.TextField()),
                ('arts_qua', models.TextField()),
                ('com_qua', models.TextField()),
                ('tec_qua', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
