# Generated by Django 5.0.6 on 2024-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
