# Generated by Django 5.0.6 on 2024-05-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicatincondition',
            old_name='Sci_sit',
            new_name='sci_sit',
        ),
    ]
