# Generated by Django 5.0.6 on 2024-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_notices_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
