# Generated by Django 5.0.6 on 2024-05-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_applyinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyinformation',
            name='roll',
        ),
    ]
