# Generated by Django 5.0.6 on 2024-05-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotsubject',
            name='hall',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
