# Generated by Django 5.0.6 on 2024-05-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_gotsubject_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotsubject',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
