# Generated by Django 5.0.6 on 2024-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_applyinformation_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsheet',
            name='resultDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
