# Generated by Django 5.0.6 on 2024-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_resultsheet_resultdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='publishDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admitcart', models.DateTimeField(blank=True, null=True)),
                ('result', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
