# Generated by Django 5.0.6 on 2024-05-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_publishdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishdate',
            old_name='Admitcart',
            new_name='admitcart',
        ),
    ]
