# Generated by Django 5.0.6 on 2024-05-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_rename_admitcart_publishdate_admitcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishdate',
            name='unit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
