# Generated by Django 5.0.6 on 2024-05-19 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('subdistrict', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=30)),
                ('ssc_board', models.CharField(max_length=40)),
                ('ssc_year', models.IntegerField()),
                ('ssc_result', models.FloatField()),
                ('hsc_board', models.CharField(max_length=40)),
                ('hsc_year', models.IntegerField()),
                ('hsc_result', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_village', models.CharField(max_length=50)),
                ('cur_subdistrict', models.CharField(max_length=40)),
                ('cur_district', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('subdistrict', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('phd', models.BooleanField()),
                ('dept', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
