# Generated by Django 5.0.4 on 2024-05-08 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_account',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user_account',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='username',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
