# Generated by Django 5.0.6 on 2024-05-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounttypes',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('superuser', 'Superuser')], max_length=20),
        ),
    ]
