# Generated by Django 5.0.6 on 2024-05-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccounttypes_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='roll_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
