# Generated by Django 5.0.6 on 2024-05-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilemodel_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='hsc_division',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='ssc_division',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
