# Generated by Django 5.0.4 on 2024-05-08 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_account_useraccounttypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('subdistrict', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('ssc_board', models.CharField(max_length=40)),
                ('ssc_year', models.IntegerField()),
                ('ssc_result', models.FloatField()),
                ('hsc_board', models.CharField(max_length=40)),
                ('hsc_year', models.IntegerField()),
                ('hsc_result', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
