# Generated by Django 5.0.4 on 2024-05-08 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_village', models.CharField(max_length=50)),
                ('cur_subdistrict', models.CharField(max_length=40)),
                ('cur_district', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('subdistrict', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('phd', models.BooleanField()),
                ('dept', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
