# Generated by Django 5.0.6 on 2024-05-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profilemodel_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='registration',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
